language: go
go:
- '1.10'
notifications:
  slack:
    secure: MkZSXLefUZzMNaLzV8BJ9Qw6zAtq0l1y277tOlFdvHrw4459KigrSUbHcizjq8xBViXjv0LexxU5eZIM48+s9R7PAUBBTSVP4vxO5DaXnTp+Lo9DZJg2hgc4+kJgBR7Ft8BgH/rDsCNTC3bnNwHYmL7It+Fp60+hVDM08JBvXlVArX8ubFmZHXImcCbTth2mk8wFtj6/ujjq0KVPrGOgzi5Xk8eK9w0QpWW0O3e6fLwEA4pwFqAfBwGDTBd1kczDGU/vaXHNXT0KMN6uKZbkncBnCW3qgjcGbG5QbXpVANaH/vX4Xw/je3JgXTXnLTvRz5EPPk8rQIpbgOtGCHqQKxnDQCZ1R9695pMyTb+slT1NYaWU3Ze3GT2938nc++nsN0s90UflufeMzJBeGXz8zsrs+c3TEMhFDzpKndphS2J2Cth22A7mrIS0CdsWhyNNZTZ6LhaPvdhnZ13HpO6AhztX4V/HnKNybx6IV0OT73KaceqoKs0QCtOKSz5Sm0ZLoeeBHjqaXDtYGWVpp06j2EvHcEHZeigB1LKNKFHNAfnAaKeQXK6QC4nZ+htXZxFxEJKEPVIw2/ZArmtaCqLC9EziS6THXvmBSQJKKoJIPeOQYgdk9k7NAuwAZAH3qAqLnyMStqteGxTI/+RYC9XzJALZgH5CSCwLvuive6/BpkY=
